name: reacuna.me
description: Random contemplations of things
author: Raúl Acuña
url: https://www.reacuna.me
timezone: America/Santiago
paginate: 10
paginate_path: "/blog/page:num/"
exclude:
  - config
  - Capfile
  - Gemfile
  - Gemfile.lock
  - README.md
plugins:
  - jekyll-feed
  - jekyll-paginate
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
sass:
  sass_dir: _sass
