---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: ''
  label: Pages
  create: all
  match: "**/*"
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
